// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2uXOpKSE5hb3nrtEGjpQ0qQO3JmRfbcM',
    appId: '1:739692658205:web:ada2e74b18ac8a92c4d0f4',
    messagingSenderId: '739692658205',
    projectId: 'flutter-auth-app-c8aba',
    authDomain: 'flutter-auth-app-c8aba.firebaseapp.com',
    storageBucket: 'flutter-auth-app-c8aba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxziEF3PKNPHa7C5TyprFrupHznvDM0tg',
    appId: '1:739692658205:android:73babcd6fe6e31b3c4d0f4',
    messagingSenderId: '739692658205',
    projectId: 'flutter-auth-app-c8aba',
    storageBucket: 'flutter-auth-app-c8aba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwenAMHF8CBN-QV8Cv86x5DAb-JRuzpcc',
    appId: '1:739692658205:ios:8ae3a49805a25ea8c4d0f4',
    messagingSenderId: '739692658205',
    projectId: 'flutter-auth-app-c8aba',
    storageBucket: 'flutter-auth-app-c8aba.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwenAMHF8CBN-QV8Cv86x5DAb-JRuzpcc',
    appId: '1:739692658205:ios:8ae3a49805a25ea8c4d0f4',
    messagingSenderId: '739692658205',
    projectId: 'flutter-auth-app-c8aba',
    storageBucket: 'flutter-auth-app-c8aba.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2uXOpKSE5hb3nrtEGjpQ0qQO3JmRfbcM',
    appId: '1:739692658205:web:3b1d5c13d6846a00c4d0f4',
    messagingSenderId: '739692658205',
    projectId: 'flutter-auth-app-c8aba',
    authDomain: 'flutter-auth-app-c8aba.firebaseapp.com',
    storageBucket: 'flutter-auth-app-c8aba.firebasestorage.app',
  );
}
